import React from "react";
import "../globals.css";
import type { Metadata } from "next";
import { Inter, Heebo } from "next/font/google";
import Sidebar from "../../components/Sidebar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { PhotoModalWrapper } from "@/context/PhotoModalContext";
import { Topbar } from "@/components";

const inter = Inter({ subsets: ["latin"] });
const heebo = Heebo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <UserProvider>
      <html lang="en" className="">
        <body className={`${inter.className} ${heebo.className} flex`}>
          <Sidebar></Sidebar>
          <div className="flex-1">
            <Topbar />
            <PhotoModalWrapper>
              {children}
              <ToastContainer />
            </PhotoModalWrapper>
          </div>
        </body>
      </html>
    </UserProvider>
  );
}
