export interface TEvent {
  id: bigint;
  createdAt?: Date;
  createdBy: string;
  eventTitle: string;
  published: boolean;
  startDateTime?: Date;
  endDateTime?: Date;
  eventVisibility?: string;
  industry: string;
  eventCategory: string;
  expectedParticipants?: bigint;
  locationType?: string;
  eventAddress?: string;
  eventCountry?: string;
  eventPoster?: Record<string, any> | null;
  organisationLogo?: string | null;
  prerequisites?: string | null;
  benefits?: Record<string, any> | null;
  pricingCurrency?: string | null;
  pricing?: Record<string, any> | null;
  organisationName?: string | null;
  country?: string | null;
  phoneNumber?: string | null;
  whatsappNumber?: string | null;
  email?: string | null;
  x?: string | null;
  linkedin?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  trainingDuration?: bigint | null;
  badgeSettings?: Record<string, any> | null;
  organisationId?: bigint | null;
  eventCity?: string | null;
  registered?: number | null;
  eventPostalCode?: string | null;
  eventTimeZone?: string | null;
  description?: Record<string, any> | null;
  partnerIndustry?: Record<string, any> | null;
}
