name: Update Fork

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows for manual triggering

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork Repository
        uses: actions/checkout@v2
        with:
          repository: ajax-484/zikoro
          ref: staging  # Change this to your default branch

      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/Ozoemenamsolomon/zikoro.git
        # Ensure this is the correct URL of the original repository

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/staging  # Change 'main' to the default branch of the original repo

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin staging  # Change 'main' to the branch you want to update